### ISSUE TITLE
A Minimum Working Example

### ISSUE THREAD

**Issue by nguyenhuyanhh** [nguyenhuyanhh/phonathon#1]
As mentioned in the Manifesto, the focus at the moment is getting a minimum working example of the system.

This issue tracks the development of the MWE.

### Initial setup
- [x] Django 1.11/ Python 3.5+
- [x] Travis CI
- [x] Flake8
- [ ] Logging (#47)

### Models
- [x] User (#6)
- [x] Prospect (#2)
- [x] Pledge (#4)
- [x] Pledge Funds (#11)
- [x] Calling Project (#30)
- [x] Calling Pool (#16)
- [x] Calling Result Codes (#22)
- [x] Call (#3)

### Authentication Framework
- [x] Groups and Permissions (#12)

### Views
- [x] Login & Logout (#26)
- [ ] The default Phonathon view (prospect details, pledge history, calling history) (#5)
- [ ] Admin dashboard (#27)

### Functionality
- [x] Smart redirect after login (#28)
- [x] Update database by csv (#7)
- [ ] Dispatch calls to callers (#15)

### Documentation
- [x] Setup instructions (#23)
- [ ] Deployment (#45)
- [x] URL configuration
- [x] Models reference (#19)
- [x] Authentication Framework (#20)
